export const questions: string[] = [
  "How healthy do you consider yourself on a scale of 1 to 10?",
  "How often do you get a health checkup?",
  "What do you say about your overall health?",
  "Do you have any chronic diseases?",
  "Do you have any hereditary conditions/diseases?",
  "Are you habitual to drugs and alcohol?",
  "Over the past 2 weeks, how often have you felt nervous,anxious, or on edge?",
  "Over the past 2 weeks, how often have you felt down,depressed, or hopeless?",
  "Over the past 2 weeks, how often have you felt little interest or pleasure in doing things?",
  "How would you describe the condition of your mouth and teeth, including false teeth or dentures?",
  "How often do you have trouble taking medicines the way you have been told to take them?",
  "On how many of the last 7 days did you engage in moderate to strenuous exercise (like a brisk walk)?",
  "Have you invested in good health insurance?",
  "Did you exposed to COVID-19?",
  "How many days did it take you to fully recover if you were exposed to COVID-19?",
  " Do you have any allergies to things like smoking, dust,etc...?",
  "Are you under work-related stress that is affecting you personal life?",
  "When did you most recently become ill or apply for a leave of absence?",
  "How many doses of the COVID vaccine you received?",
  "Please share your ideas for enhancing employee wellness at our company."
];
